
#==============#
# Camera Model #
#==============#

Camera:
  name: "Realsens D435 in RGBD mode"
  setup: "stereo"
  model: "perspective"

  #fx: 610.543579101562
  #fy: 610.674682617188
  #cx: 419.73681640625
  #cy: 242.103820800781

  fx: 424.194549560547
  fy: 424.194549560547
  cx: 428.250396728516
  cy: 238.973098754883

  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
  k3: 0.0

  fps: 30.0
  cols: 848
  rows: 480
  color_order: "Gray"
  
  focal_x_baseline: 21.21
  #depth_threshold: 305.27


#=====================#
# Tracking Parameters #
#=====================#

Tracking:
  margin_local_map_projection: 10.0
  reloc_angle_threshold: 0.45
  enable_auto_relocalization: true
  enable_temporal_keyframe_only_tracking: true

Preprocessing:
  min_size: 800
  depthmap_factor: 1000.0 # Note: Set it to 1.0 for the rosbag format data set.

#================#
# ORB Parameters #
#================#

Feature:
  name: "default ORB feature extraction setting"
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7

#====================#
# Mapping Parameters #
#====================#
Mapping:
  baseline_dist_thr: 0.07471049682
  redundant_obs_ratio_thr: 0.9

#=========================#
# LoopDetector Parameters #
#=========================#
LoopDetector:
  enabled: true


